### ISSUE TITLE
Can't use "random" and probably can't actually import anything

### ISSUE THREAD

**Issue by vinovak** [grongor/vito-lang#1]
```
Budeme používat random
čosi teď bude ['a', 'b', 'c']
Volám Čuprovi(random.choice(čosi))
```

will produce:

```
$ chci random.nohy 
import random
čosi teď bude ['a', 'b', 'c']
print(random.choice(čosi))

Unknown command "and" used. This is not a VitoLang construct.
```

And even if we try to import something else, it produces:

`Unknown command "or" used. This is not a VitoLang construct.`

bacause apearantly code is checked after "Budeme používat" is already translated to "import" and there is "or" in "import".

Also, if we would succesfully import random library, how do I use it? Can I somehow concatenate namespace name? I can't call "ran + dom.choice()" to precent intepreter from finding "and", can I?

**Comment by malvex** [comment]
Because of what happened, I actually created tests for vitolang interpreter (more PR #3). Just to be sure it works and everything can be written in it.

**Comment by vinovak** [comment]
Awesome work, gentleman! It works perfectly now! So I'm going to go on enjoying this great product ;) Thanks!
