### ISSUE TITLE
"input()" does not work as expected

### ISSUE THREAD

**Issue by vinovak** [grongor/vito-lang#4]
```
kdo teď bude input('Kurva kdo!? ')
Volám Čuprovi('Kurva ' + kdo)
```

at first produces:

```
$ chci input-test.nohy

```

(just empty line, waiting for input prior to printing `Kurva kdo!?`)

and AFTER the input (I typed `já`) it goes on:

```
$ chci input-test.nohy
já
Kurva kdo!? Kurva já
```

So am I doing something wrong here?

**Comment by grongor** [comment]
Hmm, interesting bug. I'll try to reproduce the bug and then get back to you soon.

**Comment by grongor** [comment]
The bug is confirmed - I was able to reproduce your results. I will try to fix it ASAP.

**Comment by grongor** [comment]
Funny thing ... after 2 hours of playing with file descriptors, ptys, fcntl and other nice things I discovered incredibly simple fix. Wow, why is that people are always looking for the hard way first? I will upload the fix in a moment :-)

**Comment by vinovak** [comment]
Excelent work again! Thanks!
